
    import React from 'react';
    import MainMenu from '../components/MainMenu';

    const Glossary = () => {
      const terms = [
        { term: "10GBase-SR", definition: "IEEE 802.3an Standard for 'Short Reach' using 850nm lasers can transmit up to 300 metres using 50 micron OM3 multimode fibre." },
        { term: "10GBase-LR", definition: "IEEE 802.3an Standard for 'Long Reach' using 1310nm lasers can transmit up to 10km using OS1 Single mode fibre." },
        { term: "10GBase-T", definition: "IEEE 802.3an Standard released in 2006, to provide 10Gbit/s Ethernet connections over unshielded or shielded twisted pair cables, over distances up to 100 metres." },
        { term: "1000Base-LX", definition: "IEEE 802.3 shorthand term for 1000 Mbps Gigabit Ethernet based on 8B/10B signaling using long wavelength laser transmitters over fibre optic cable." },
        { term: "1000Base-SX", definition: "IEEE 802.3 shorthand term for 1000 Mbps Gigabit Ethernet based on 8B/10B signaling using short wavelength laser transmitters over fibre optic cable." },
        { term: "1000Base-T", definition: "IEEE 802.3 shorthand term for 1000 Mbps Gigabit Ethernet over twisted pair cable." },
        { term: "1000Base-X", definition: "IEEE 802.3 shorthand term for any 1000 Mbps Gigabit Ethernet based on 8B/10B signaling. Includes 1000Base-CX, 1000Base-LX and 1000Base-SX." },
        { term: "100Base-FX", definition: "IEEE 802.3 shorthand term for 100 Mbps Fast Ethernet based on 4B/5B signal encoding over fibre optic cable." },
        { term: "100Base-T", definition: "IEEE 802.3 shorthand term for entire 100 Mbps Fast Ethernet system." },
        { term: "100Base-TX", definition: "IEEE 802.3 shorthand term for 100 Mbps Fast Ethernet based on 4B/5B signal encoding and using two pairs of category 5 twisted pair cable." },
        { term: "100Base-X", definition: "IEEE 802.3 shorthand term for any 100 Mbps Fast Ethernet system based on 4B/5B signal encoding. Includes 100Base-TX and 100Base-FX." },
        { term: "10Base2", definition: "IEEE 802.3 shorthand term for 10 Mbps Ethernet based on Manchester signal encoding over thin coaxial cable. Also called 'Thinnet' or 'Cheapernet'." },
        { term: "10Base5", definition: "IEEE 802.3 shorthand term for 10 Mbps Ethernet based on Manchester signal encoding over thick coaxial cable. Also called 'Thicknet'." },
        { term: "10Base-T", definition: "IEEE 802.3 shorthand term for 10 Mbps Ethernet based on Manchester signal encoding over category 3 or better twisted pair cable." },
        { term: "10Base-T1S", definition: "IEEE 802.3 shorthand term for 10 Mbps Ethernet over Single Pair, Short Reach." },
        { term: "10Base-T1L", definition: "IEEE 802.3 shorthand term for 10 Mbps Ethernet over Single Pair, Long Reach up to 1Km." },
        { term: "100Base-T1S", definition: "IEEE 802.3 shorthand term for 100Mbps Ethernet over Single Pair, Short Reach." },
        { term: "ACP", definition: "Area Connection Point." },
        { term: "ANSI", definition: "American National Standards Institute." },
        { term: "Asynchronous", definition: "Transmission where sending and receiving devices are not synchronized. Data must carry signals to indicate data division." },
        { term: "ATM", definition: "Asynchronous Transfer Mode. A networking protocol which can support multimedia (i.e. Voice, data, video, text etc.) communications." },
        { term: "Attenuation", definition: "The decrease in magnitude of a signal as it travels through any transmission medium such as a cable or optical fibre. Measured in dB per unit of length." },
        { term: "ACR (Attenuation Crosstalk Ratio)", definition: "The difference between attenuation and crosstalk, measured in dB, at a given frequency. A quality factor for cabling to assure that signal sent down a twisted pair is stronger at the receiving end of the cable than any interference imposed on the same pair by crosstalk from other pairs." },
        { term: "ACR-F", definition: "Attenuation Crosstalk Ratio Far End." },
        { term: "AWG", definition: "American Wire Gage - A wire diameter specification. The smaller the AWG number, the larger the wire diameter." },
        { term: "Back reflection", definition: "The light reflected back towards the source from the fibre optic ends and deformations." },
        { term: "Backscatter", definition: "Another term for Back Reflection, reflection of signal back to the direction from which they came." },
        { term: "Backbone", definition: "Term used to refer to the common central elements of any communications network. The backbone is the part of the network which connects all the individual network components." },
        { term: "Bandwidth", definition: "The range of frequencies required for proper transmission of a signal. Expressed in Hertz (cycles per second). The higher the bandwidth, the more information that can be carried." },
        { term: "Baud", definition: "The number of changes in signal per second. A given baud rate does not necessarily transmit an equal number of bits/sec." },
        { term: "BD", definition: "Building Distributor - main comms room for distribution of services throughout the building." },
        { term: "BEF", definition: "Building Entrance Facility - used by service providers such as BT, Virgin Media etc." },
        { term: "Bend Loss", definition: "A form of increased attenuation in an optical fibre caused by an excessively small bend radius. The attenuation may be permanent if micro fractures caused by the bend continue to affect transmission of the light signal." },
        { term: "Bend Radius", definition: "Radius of curvature that a fibre optic or metallic cable can bend before the risk of breakage or increased attenuation occurs." },
        { term: "BICSI", definition: "Building Industry Consulting Service International." },
        { term: "Bit", definition: "One binary digit." },
        { term: "BER (Bit Error Rate)", definition: "A measure of data integrity, expressed as the ratio of received bits that are in error, relative to the amount of bits received. Often expressed as a negative power of ten." },
        { term: "Bit Stream", definition: "A continuous transfer of bits over some medium." },
        { term: "BMS", definition: "Building Management System." },
        { term: "BNC", definition: "A coaxial connector that uses a 'bayonet' style turn and lock mating method. Used with RG58 or smaller coaxial cable. Used with 10Base2 Ethernet thin coaxial cable. BNC is an acronym for Bayonet Neill Concelman." },
        { term: "BO", definition: "Broadcast Outlet (TV Outlet)." },
        { term: "BOYD", definition: "Bring your own device'." },
        { term: "BPS", definition: "Bits per second." },
        { term: "Braid", definition: "Fine wires interwoven to form a tubular flexible structure that may be applied over one or more wires for the purpose of shielding." },
        { term: "BRI", definition: "ISDN Basic Rate Interface." },
        { term: "Broadband", definition: "A transmission facility having a bandwidth sufficient to carry multiple voice, video or data channels simultaneously." },
        { term: "Broadcast", definition: "Sending data to more than one receiving device at a time." },
        { term: "Buffer", definition: "A protective coating over a strand of optical fibre." },
        { term: "Bus Topology", definition: "In general, a physical layout of network devices in which all devices must share a common medium to transfer data, and no two devices may transmit simultaneously." },
        { term: "Byte", definition: "A group of 8 bits." },
        { term: "Campus", definition: "The buildings and grounds of a complex, such as a university, college, industrial park or military establishment." },
        { term: "Carrier", definition: "An electrical signal of a set frequency that can be modulated in order to carry data." },
        { term: "Category 3, Cat 3", definition: "Balanced twisted-pair copper cable and component specifications characterised in a frequency range up to 16 MHz. with a characteristic Impedance of 100Ohm." },
        { term: "Category 5e, Cat 5e", definition: "Balanced twisted-pair copper cable and component specifications characterised in a frequency range up to 100 MHz. with a characteristic Impedance of 100Ohm." },
        { term: "Category 6, Cat 6", definition: "Balanced twisted-pair copper cable and component specifications characterised in a frequency range up to 250 MHz. with a characteristic impedance of 100Ohm." },
        { term: "Category 6A, Cat 6A", definition: "Balanced twisted-pair copper cable and component specifications characterised in a frequency range up to 500 MHz. with a Characteristic impedance of 100Ohm." },
        { term: "Category 7, Cat 7", definition: "Balanced twisted-pair copper cable and component specifications characterised in a frequency range up to 600 MHz. with a characteristic impedance of 100Ohm." },
        { term: "Category 7A, Cat 7A", definition: "Balanced twisted-pair copper cable and component specifications characterised in a frequency range up to 1000 MHz.(1Ghz) with a characteristic Impedance of 100Ohm." },
        { term: "Category 8, Cat 8", definition: "Whilst not yet ratified this is intended to support short 40Gb links within the Data Centre environment. It will be a balanced twisted-pair copper cable and component specifications characterised in a frequency range of up to 2GHz with a characteristic Impedance of 100Ohm." },
        { term: "CATV", definition: "Community Antenna Television." },
        { term: "CCTV", definition: "Closed Circuit TV." },
        { term: "CD", definition: "Campus Distributor - Main campus communication room or facility." },
        { term: "CDDI", definition: "Copper Distributed Data Interface. A version of FDDI that uses copper wire media instead of fibre optic cable." },
        { term: "CENELEC", definition: "European Committee for Electrotechnical Standardization." },
        { term: "Channel", definition: "The end to end transmission path between two points at which application specific equipment is connected." },
        { term: "Channel Insertion Loss", definition: "For fibre optic links, the static loss of a link between a transmitter and receiver. It includes the loss of the fibre, connectors, and splices." },
        { term: "Characteristic Impedance", definition: "The impedance that an infinitely long transmission line would have at its input terminal. If a transmission line is terminated in its characteristic impedance, it will appear (electrically) to be infinitely long, thus minimizing signal reflections from the end of the line." },
        { term: "Chromatic Dispersion", definition: "Synonym for 'material dispersion'. Characteristic of long fibre runs." },
        { term: "CIBSE", definition: "Chartered Institution of Building Service Engineers." },
        { term: "Class C", definition: "ISO/IEC 11801 designation for twisted pair cabling rated to 16 MHz. Corresponds to the TIA/EIA Category 3 cabling standard." },
        { term: "Class D", definition: "ISO/IEC 11801 designation for twisted pair cabling rated to 100 MHz. Using Category 5e components it corresponds to the TIA/EIA Category 5e cabling standard." },
        { term: "Class E", definition: "ISO/IEC 11801 designation for twisted pair cabling rated to 250 MHz. Using Category 6 components it corresponds to the TIA/EIA Category 6 cabling standard." },
        { term: "Class EA", definition: "ISO/IEC 11801 designation for twisted pair cabling rated to 500 MHz. Using Category 6A components it corresponds to the TIA/EIA Category 6A cabling standard." },
        { term: "Class F", definition: "ISO/IEC 11801 designation for twisted pair cabling rated to 600 MHz, TIA/EIA does not recognise Category 7." },
        { term: "Class FA", definition: "ISO/IEC 11801 designation for twisted pair cabling rated to 1000 MHz. (1Ghz) TIA/EIA does not recognise Category 7A." },
        { term: "Class I", definition: "ISO/IEC 11801 designation for twisted pair cabling rated to 1600 MHz. (1.6Ghz) this does not correspond to TIA/EIA Category 8 cabling standard." },
        { term: "Class II", definition: "ISO/IEC 11801 designation for twisted pair cabling rated to 2000 MHz. (2Ghz) this does correspond to the TIA/EIA Category 8 cabling standard." },
        { term: "CLI", definition: "Calling Line Identity. The term used to describe the feature whereby the telephone number of a calling party is presented to the equipment of the called party." },
        { term: "CDCDP", definition: "Certified Data Centre Design Professional." },
        { term: "CDCTP", definition: "Certified Data Centre Technical Professional." },
        { term: "CNCI", definition: "Certified Network Cable Installer." },
        { term: "CNIT", definition: "Certified Network Infrastructure Technician." },
        { term: "CNID", definition: "Certified Network Infrastructure Designer." },
        { term: "CNIDP", definition: "Certified Network Infrastructure Design Professional." },
        { term: "CO", definition: "Control Outlet - outlet used by the Building Control System such as BMS." },
        { term: "Coax, Coaxial Cable", definition: "A type of communication transmission cable in which a solid center conductor is surrounded by an insulating spacer which in turn is surrounded by a tubular outer conductor (usually a braid, foil or both). The entire assembly is then covered with an insulating and protective outer layer." },
        { term: "Collision", definition: "When electrical signals from two or more devices sharing a common data transfer medium crash into one another. This commonly happens on Ethernet type systems." },
        { term: "Conductor", definition: "A material that offers low resistance to the flow of electrical current." },
        { term: "Conduit", definition: "A rigid or flexible metallic or nonmetallic raceway of circular cross section in which cables are housed for protection and to prevent burning cable from spreading flames or smoke in the event of a fire." },
        { term: "Consolidation Point (CP)", definition: "A CP is a location for interconnection between the permanently installed horizontal cables the TR and the horizontal cables extending to the telecommunications outlet (TO)." },
        { term: "Continuity", definition: "An uninterrupted pathway for electrical signals." },
        { term: "Core", definition: "The central region of an optical fibre through which light is transmitted." },
        { term: "CPD", definition: "Continuing Professional Development." },
        { term: "CPR", definition: "Construction Products Regulation." },
        { term: "CPR", definition: "Coupled Power Ratio which is used when testing optical fibre cables." },
        { term: "Cross Connect", definition: "A facility enabling the termination of cable elements and their interconnection, and/or cross connection, primarily by means of a patch cord or jumper." },
        { term: "Cross Connection", definition: "A connection scheme between cabling runs, subsystems, and equipment using patch cords or jumpers that attach to connecting hardware at each end." },
        { term: "Crossover Cable", definition: "A twisted pair patch cable wired in such a way as to route the transmit signals from one piece of equipment to the receive signals of another piece of equipment, and vice versa." },
        { term: "Crosstalk", definition: "The coupling of unwanted signals from one pair within a cable to another pair. Crosstalk can be measured at the same (near) end or far end with respect to the signal source." },
        { term: "CSMA/CD", definition: "Carrier Sense Multiple Access with Collision Detect." },
        { term: "CTI", definition: "Computer Telephony Integration. The integration of computer and telephone systems to support intelligent applications." },
        { term: "Customer Premises", definition: "Buildings, offices, and other structures under the control of a telecommunications customer." },
        { term: "CWDM", definition: "Course Wavelength Disiion Multiplexing." },
        { term: "CW1128", definition: "External grade multipair voice cable that meets the (BT) British Telecom specification." },
        { term: "CW1308", definition: "Internal grade multipair voice cable that meets the (BT) British Telecom specification." },
        { term: "CW1308B", definition: "Internal/External, with earth grade multipair voice cable that meets the (BT) British Telecom specification." },
        { term: "Data Connector", definition: "A four position connector for 150 - ohm STP used primarily with Token Ring networks." },
        { term: "dB", definition: "Decibel. A unit for measuring the relative strength of a signal. Usually expressed as the logarithmic ratio of the strength of a transmitted signal to the strength of the original signal. A decibel is one tenth of a 'bel'." },
        { term: "DC Loop Resistance", definition: "The total DC resistance of a cable. For twisted pair cable, it includes the round trip resistance, down one wire of the pair and back up the other wire." },
        { term: "DCE", definition: "Data Communications Equipment. Any equipment that connects to Data Terminal Equipment (DTE) to allow transmission between DTEs." },
        { term: "DCIE", definition: "Data Centre Infrastructure Efficiency." },
        { term: "DDI", definition: "Direct Dialing Inward. This facility enables external callers to dial directly to PABX extensions (without going via the switchboard) by inserting a prefix in front of the extension number." },
        { term: "Demarcation Point", definition: "A point where the operational control or ownership changes, such as the point of interconnection between telephone company facilities and a user's building or residence." },
        { term: "Dielectric", definition: "An insulating (non conducting) material." },
        { term: "Direct Current (DC)", definition: "An electric current that flows in one direction and does not reverse direction as with 'alternating current'." },
        { term: "Dispersion", definition: "The phenomenon in an optical fibre whereby light photons arrive at a distant point in a different phase than they entered the fibre. Dispersion causes receive signal distortion that ultimately limits the bandwidth and usable length of the fibre cable." },
        { term: "Distribution Frame", definition: "A structure with terminations for connecting the permanent cabling of a facility in a manner that interconnections or cross connects may be readily made." },
        { term: "Drain Wire", definition: "An uninsulated wire in contact with a shield throughout its length. Used to terminate the shield." },
        { term: "DTE", definition: "Data Terminal Equipment. Any piece of equipment at which a communications path begins or ends." },
        { term: "Duct", definition: "A single enclosed raceway for wires or cable or an enclosure in which air is moved." },
        { term: "Duplex", definition: "A circuit used to transmit signals simultaneously in both directions or two receptacles or jacks in a common housing which accept two plugs." },
        { term: "DWDM", definition: "Dense Wavelength Division Multiplexing." },
         { term: "E1/E3", definition: "The European versions of T1 and T3. E1 runs at 2.048 Mbps and E3 runs at 34 Mbps." },
    { term: "Earth", definition: "A term for zero reference ground." },
    { term: "EC", definition: "European Community" },
    { term: "EIA", definition: "Electronic Industry Association (formerly RMA or RETMA). An association of manufacturers and users that establishes standards and publishes test methodologies." },
    { term: "Electromagnetic Field", definition: "The combined electric and magnetic field caused by electron motion in conductors." },
    { term: "Electromagnetic Interference", definition: "An interfering electromagnetic signal. Network wiring and equipment may be susceptible to EMI as well as emit EMI." },
    { term: "ELFEXT", definition: "Equal Level Far End Crosstalk - superseded by ACR-F" },
    { term: "EMI", definition: "see Electromagnetic Interference." },
    { term: "Encircled Flux - EF", definition: "Fraction of cumulative near-field power to the total output as a function of radial distance from the optical centre of the core." },
    { term: "Encoding", definition: "A means of combining clock and data information into a self synchronized stream of signals." },
    { term: "ENI", definition: "External Network Interface - link to external internet providers service." },
    { term: "Entrance Facility (EF)", definition: "The point at which the ISP or Service Providers cables enter the building." },
    { term: "Environ®", definition: "Floor standing and wall mounted racks and frames from Excel." },
    { term: "Equipment Room (ER)", definition: "An enclosed area housing telecommunications and network equipment, distinguished from the telecommunications or wiring closet by its increased complexity and presence of active equipment." },
    { term: "Ethernet", definition: "A local area networking protocol. Ethernet was designed as a common bus system operating at 10Mbit/s. Ethernet Switches are commonly used to support a star based topology with speeds of up to 10Gbs over twisted pair cabling." },
    { term: "Far End Cross Talk (FEXT)", definition: "Crosstalk that is measured on the quiet line at the opposite end as the source of energy on the active line. FEXT is not typically measured in cabling, with Near End Cross Talk (NEXT) being the preferred crosstalk measurement." },
    { term: "Farad", definition: "A unit of capacitance that stores one coulomb of electrical charge when one volt of electrical pressure is applied." },
    { term: "Fast Ethernet", definition: "Ethernet standard supporting 100 Mbps operation." },
    { term: "FAT", definition: "Fibre Access Terminal" },
    { term: "Fibre Channel", definition: "Fibre Channel or FC is a high speed network technology running at 2, 4, 8 or 16 Gbs primarily used to connect Data Storage or SANs (Storage Area Networks)." },
    { term: "FD", definition: "Floor Distributor for distribution of service throughout the floor of a building." },
    { term: "FDDI", definition: "Fibre Distributed Data Interface. FDDI is a 100Mbit/s networking protocol which operates over optical fibre. FDDI was initially developed as a MAN protocol but is also commonly supported in the LAN environment." },
    { term: "FEXT", definition: "see Far End Cross Talk" },
    { term: "Frequency", definition: "The number of times a periodic action occurs in a unit of time. Expressed in hertz (abbreviated Hz). One hertz equals one cycle per second." },
    { term: "Frequency Division Multiplexing (FDM)", definition: "A technique for combining many signals on a single circuit by dividing the available transmission bandwidth by frequency into narrower bands, each used for a separate communication channel." },
    { term: "F/UTP", definition: "Screened cable construction, of overall Foil outer with unscreened twisted pairs." },
    { term: "F/FTP", definition: "Screened foil outer with individual screened foil twisted pairs" },
    { term: "FTTC", definition: "Fibre to the Kerb (Curb US spelling) last section into the home would be copper" },
    { term: "FTTH", definition: "Fibre to the home - Fibre into the home" },
    { term: "FTTN", definition: "Fibre to the Node - Typically street furniture serving multiple homes" },
    { term: "FTTx", definition: "Generic term covering the above" },
    { term: "Full Duplex Transmission", definition: "Data transmission over a circuit capable of transmitting in both directions simultaneously." },
    { term: "Gateway", definition: "A term used for a device which enables two networks to communicate with each other. The term strictly refers to a device which undertakes a protocol conversion between two non-like networks. However, it is now commonly applied to any device which acts as an access point between networks even if no protocol conversion is necessary (e.g. internet gateway)." },
    { term: "Gbps", definition: "Gigabits per second." },
    { term: "Gigahertz (GHz)", definition: "One billion hertz." },
    { term: "GIPOF", definition: "Graded Index Plastic Optical Fibre" },
    { term: "GOP", definition: "Grid Outlet Position" },
    { term: "GPON", definition: "Gigabit Passive Optical Network" },
    { term: "Graded Index fibre", definition: "A multimode fibre optic cable design in which the index of refraction of the core is lower toward the outside of the core and progressively increases toward the centre of the core, thereby reducing modal dispersion of the signal." },
    { term: "Ground", definition: "A common point of zero potential such as a metal chassis or ground rod." },
    { term: "Ground Loop", definition: "A condition where an unintended connection to ground is made through an interfering electrical conductor." },
    { term: "Half Duplex Transmission", definition: "Data transmission over a circuit capable of transmitting in either direction, but not simultaneously." },
    { term: "HBES", definition: "Home & Building Electronic System - Residential version of BMS." },
    { term: "HD", definition: "Home Distributor - Residential version of main buildings distributor used in commercial buildings." },
    { term: "Headroom", definition: "The amount by which a cable exceeds NEXT." },
    { term: "Hertz", definition: "The unit of frequency, one cycle per second (abbreviated Hz)." },
    { term: "Horizontal Cabling, Horizontal Wiring", definition: "The portion of the cabling system that extends from the work area outlet to the horizontal cross connect in the telecommunications or wiring closet." },
    { term: "Horizontal Cross Connect", definition: "A cross connect of horizontal cabling to other cabling, e.g. horizontal, backbone, or equipment." },
    { term: "http", definition: "Hyper Text Transfer Protocol, used for WWW documents." },
    { term: "Hub", definition: "A device which is utilised to connect multiple other devices. The most common application is an Ethernet hub which is used to support star based Ethernet topologies." },
    { term: "HVAC", definition: "Heating, ventilation, and air conditioning system." },
    { term: "IC", definition: "see Intermediate Cross Connect." },
    { term: "ICEA", definition: "Insulated Cable Engineers Association" },
    { term: "IDC", definition: "Insulation Displacement Contact/Connector" },
    { term: "IDF", definition: "Intermediate Distribution Frame. This is usually located on each floor within a building. It is tied directly to the Main Distribution Frame via cables." },
    { term: "IEC", definition: "International Electrotechnical Commission" },
    { term: "IEEE", definition: "Institute of Electrical and Electronics Engineers. A professional organization and standards body. The IEEE Project 802 is the group within IEEE responsible for LAN technology standards." },
    { term: "IEEE 802.1", definition: "The IEEE standards committee defining High Level Interfaces, Network Management, Inter-networking, and other issues common across LAN technologies." },
    { term: "IEEE 802.2", definition: "The IEEE standards committee defining Logical Link Control (LLC)." },
    { term: "IEEE 802.3", definition: "The IEEE standards committee defining Ethernet networks." },
    { term: "IEEE 802.3at", definition: "High power Power over Ethernet or PoE+ delivering 25.5 watts. From PSE" },
    { term: "IEEE 802.3bt", definition: "4 Pair Power over Ethernet or 4PPoE Type3 delivers 60 watts from PSE, Type 4 delivers up to 90watts" },
    { term: "IEEE 802.3bu", definition: "Power over Data Line or PoDL (pronounced ‘Poodle’) different to PoE and used with Single Pair Ethernet." },
    { term: "IEEE 802.3cg", definition: "Single Pair Ethernet Standard" },
    { term: "IEEE 802.5", definition: "The IEEE standards committee defining Token Ring Standards" },
    { term: "IEEE 802.11", definition: "The IEEE standards committee defining Wireless Local Area Network Standards, WiFi Communications" },
    { term: "IEEE 802.11b", definition: "Wireless Lan, 11Mbps at 2.4GHz" },
    { term: "IEEE 802.11g", definition: "Wireless Lan, 54Mbps at 5GHz" },
    { term: "IEEE 802.11n", definition: "Wireless Lan, 65Mbps to 600Mbps at 2.4 or 5GHz" },
    { term: "IEEE 802.11ac", definition: "Wireless Lan, 78Mbps to 3.2Gbps at 5GHz" },
    { term: "IEEE 802.11ax", definition: "Wireless Lan, 600Mbps to 9.6Gbps at 2.4 & 5GHz" },
    { term: "Impedance", definition: "A unit of measure, expressed in Ohms, of the total opposition (resistance, capacitance and inductance) offered to the flow of an alternating current." },
    { term: "Insertion Loss", definition: "A measure of the attenuation of a device by determining the output of a system before and after the device is inserted into the system. For example, a connector causes insertion loss across the interconnection (in comparison to a continuous cable with no interconnection)." },
    { term: "Insulation", definition: "A material which is nonconductive to the flow of electrical current." },
    { term: "Interconnection", definition: "A connection scheme that provides for the direct connection of a cable to another cable or to an equipment cable without a patch cord or jumper." },
    { term: "Interference", definition: "Undesirable signals which interfere with the normal operation of electronic equipment or electronic transmission." },
    { term: "Intermediate Cross Connect", definition: "A cross connect between 1st level and 2nd level backbone cabling." },
    { term: "Intranet", definition: "A closed user group internet which uses browser style interfaces to present information. An intranet may either exist only within a private network or may be accessible via the internet." },
    { term: "IP", definition: "Internet Protocol. Now becoming the dominant protocol for WANs and LANs." },
    { term: "ISDN", definition: "Integrated Services Digital Network. The ISDN is the modern, digital equivalent of the PSTN. It employs digital technology throughout and can be used to support multimedia communications including voice, data, video and image. Two narrow band ISDN products are commonly available in the UK; basic rate (2B+D, 144Kbit/s, ISDN2) and primary rate (30B+D, 2Mbit/s). Broadband services will become available in the future." },
    { term: "ISDN2e", definition: "BT’s European ISDN 2B+D service." },
    { term: "ISO", definition: "International Organisation for Standardisation - publishers of international standards." },
    { term: "Isolated Ground", definition: "A separate ground conductor which is insulated from the equipment or building ground." },
    { term: "ISP", definition: "Internet Service Provider. Companies who provide access to the internet. Access may be via dial-up modems basic rate ISDN or digital leased lines." },
    { term: "IT", definition: "Common abbreviation for the generic term “information technology” used to describe any aspect of computing and networking." },
    { term: "ITU", definition: "International Telecommunications Union. An international organization that develops communications standards." },
    { term: "Jack", definition: "A female connector" },
    { term: "Jacket", definition: "The outer protective covering of a cable." },
    { term: "Jumper", definition: "An assembly of twisted pairs without connectors used to used to join telecommunications circuits at the cross connect. Similar to a patch cable (which has connectors)." },
    { term: "Keying", definition: "The mechanical feature of a connector system that guarantees correct orientation of a connection, or prevents the connection to a jack, or to an optical fibre adapter, of the same type intended for another purpose." },
    { term: "LAN", definition: "Local Area Network" },
    { term: "Laser", definition: "Light Amplification by Stimulated Emission of Radiation. A device which produces light with a narrow spectral width. Used in fibre optic communication systems, usually single mode, where high capacity and low attenuation are required." },
    { term: "LC (SFF)", definition: "Small Form Factor fibre connector, currently the most common connector used for premise cabling installations, due to the high density that can be achieved, uses a 1.25mm ferrule, LC stands for ‘Lucent Connector’" },
    { term: "Leased Line", definition: "A circuit rented from a PTO. A leased line provides permanent guaranteed bandwidth between two locations." },
    { term: "LED (Light Emitting Diode)", definition: "A semiconductor diode which emits incoherent light when a current is passed through it. Used as a light source in fibre optic transmission." },
    { term: "Link", definition: "A transmission path between two points not including terminal equipment, work area cables, or equipment cables." },
    { term: "Loopback", definition: "A type of diagnostic test in which a transmitted signal is returned to the sending device after passing through a data communications link or network. This test allows the comparison of a returned signal with the transmitted signal." },
    { term: "LSOH", definition: "Low Smoke Zero Halogen - refers to compound construction. Usually cable sheath or flexible conduit." },
    { term: "LSPM", definition: "Light Source & Power Meter" },
    { term: "mA", definition: "Milliampere (one thousandth of an ampere)" },
    { term: "Main Cross Connect", definition: "A cross connect for first level backbone cables, entrance cables, and equipment cables. The main cross connect is at the top level of the premises cabling tree." },
    { term: "MAN", definition: "Metropolitan Area Network. Strictly a term used to define a network throughout a metropolitan area. Such a network would generally be PTO provided. However the term is now commonly used to describe an extended LAN which serves a number of buildings in a restricted geographical area." },
    { term: "MATO", definition: "Multi Application Telecommunications Outlet." },
    { term: "Mbps", definition: "Megabits per second." },
    { term: "MDF", definition: "Main Distribution Frame" },
    { term: "Medium Access Control (MAC)", definition: "A mechanism operating at the data link layer of local area networks which manages access to the communications channel (medium)." },
    { term: "Medium Dependent Interface (MDI)", definition: "In Ethernet, the connector used to make the mechanical and electrical interface between a transceiver and a media segment. An 8 pin RJ 45 connector is the MDI for the 10BaseT, 100BaseTX, 100BaseT2, 100BaseT4, and 1000BaseT media systems." },
    { term: "Medium Independent Interface (MII)", definition: "Used with 100 Mbps Ethernet systems to attach MAC level hardware to a variety of physical media systems. Similar to the AUI interface used with 10 Mbps Ethernet systems. An MII provides a 40 pin connection to outboard transceivers (also called PHY devices)." },
    { term: "Megahertz (MHz)", definition: "One million hertz." },
    { term: "MER", definition: "Main Equipment Room" },
    { term: "Micro", definition: "Prefix meaning one millionth." },
    { term: "Micron", definition: "One millionth of a meter. Abbreviated µm." },
    { term: "Modal Dispersion", definition: "Dispersion that results from the different transit lengths of different propagating modes in a multimode optical fibre." },
    { term: "Mode", definition: "A single electromagnetic wave travelling in an optical fibre." },
    { term: "Modem", definition: "A device that implements “modulator demodulator” functions to convert between digital data and analogue signals." },
    { term: "Modular Jack", definition: "The equipment mounted half of a modular interconnection. Typically a female connector. A modular jack may be keyed or unkeyed and may have six or eight contact positions, but not all the positions need to be equipped with jack contacts." },
    { term: "Modular Plug", definition: "The cable mounted half of a modular interconnection. Typically a male connector. A modular plug may be keyed or unkeyed and may have six or eight contact positions, but not all the positions need to be equipped with contacts." },
    { term: "MPO", definition: "Multi-fibre connector, designated stands for Multi-Fibre Push On Pull Off" },
    { term: "MTP", definition: "Low Loss MPO connector produced by US Conec" },
    { term: "Multimode Fibre", definition: "A fibre optic cable which supports the propagation of multiple modes. Multimode fibre may have a typical core diameter of 50 or 62.5 micron to 100 µm with a refractive index that is graded or stepped. It allows the use of inexpensive LED light sources and connector alignment and coupling is less critical than single mode fibre. Distances of transmission and transmission bandwidth are less than with single mode fibre due to dispersion." },
    { term: "mV", definition: "Millivolt (one thousandth of a volt)" },
    { term: "mW", definition: "Milliwatt (one thousandth of a watt)" },
    { term: "Nanometer (nm)", definition: "One billionth of a metre." },
    { term: "Nanosecond (ns)", definition: "One billionth of a second." },
    { term: "NB", definition: "Notified Body" },
    { term: "NEXT (Near End Crosstalk)", definition: "Crosstalk between two twisted pairs measured at the same end of the cable as the disturbing signal source. NEXT is the measurement of interest for crosstalk specifications." },
    { term: "Network", definition: "An interconnection of computer systems, terminals or data communications facilities." },
    { term: "Network Interface Card", definition: "A circuit board installed in a computing device used to attach the device to a network. A NIC performs the hardware functions that are required to provide a computing device with physical communications capabilities. Also Network Interface Unit (NIU)." },
    { term: "NFPA", definition: "National Fire Protection Association" },
    { term: "NIR", definition: "Nearend Crosstalk to Insertion Loss Ratio" },
    { term: "Node", definition: "End point of a network connection. Nodes include any device connected to a network such as file servers, printers, or workstations." },
    { term: "NVP", definition: "Nominal Velocity of Propagation. The speed a signal propagates through a cable expressed as a decimal fraction of the speed of light in a vacuum." },
    { term: "Octet", definition: "8 bits (also called a byte)." },
    { term: "OF", definition: "Open" },
    { term: "OFTEL", definition: "Office of Telecommunications. The Government appointed watchdog organisation in the UK." },
    { term: "Ohm", definition: "The electrical unit of resistance. The value of resistance through which a potential of one volt will maintain a current of one ampere." },
    { term: "Ohm’s Law", definition: "Stated E=IR, I=E/R, or R=E/I, the current “I” in a circuit is directly proportional to the voltage “E”, and inversely proportional to the resistance “R”." },
    { term: "OLT", definition: "Optical Line Terminal" },
    { term: "OLTS", definition: "Optical Loss Test Set, see LSPM" },
    { term: "ONT", definition: "Optical Network Terminal" },
    { term: "Open", definition: "A break in the continuity of a circuit." },
    { term: "Optical Fibre", definition: "A thin glass or plastic filament used for the transmission of information via light signals. The signal carrying part of a fibre optic cable." },
    { term: "Optical Fibre Cable", definition: "An assembly consisting of one or more optical fibres." },
    { term: "Optical Fibre Duplex Adapter", definition: "A mechanical media termination device designed to align and join two duplex connectors." },
    { term: "Optical Fibre Duplex Connection", definition: "A mated assembly of two duplex connectors and a duplex adapter." },
    { term: "Optical Fibre Duplex Connector", definition: "A mechanical media termination device designed to transfer optical power between two pairs of optical fibres." },
    { term: "Optical Time Domain Reflectometry", definition: "A method for evaluating optical fibre based on detecting and measuring backscattered (reflected) light. Used to measure fibre length and attenuation, evaluate splice and connector joints, locate faults, and certify cabling systems." },
    { term: "OSI", definition: "Open Systems Interconnection" },
    { term: "OTDR", definition: "Optical Time Domain Reflectometry." },
    { term: "Outlet", definition: "See Telecommunications Outlet" },
    { term: "Outlet Box", definition: "A metallic or non metallic box mounted within a wall, floor, or ceiling used to hold outlet, connector, or transition devices." },
    { term: "Output", definition: "The useful signal or power delivered by a circuit or device." },
    { term: "Outside Plant", definition: "Cabling, equipment, or structures that are out of doors." },
    { term: "PABX", definition: "Private Automatic Branch Exchange" },
    { term: "Packet", definition: "Bits grouped serially in a defined format, containing a command or data message sent over a network." },
    { term: "Patch Panel", definition: "A passive device, typically flat plate holding feed through connectors, to allow circuit arrangements and rearrangements by simply plugging and unplugging patch cables." },
    { term: "Patch Cord (Patch Lead)", definition: "A flexible piece of cable terminated at both ends with connectors. Used for interconnecting circuits on a patch panel or cross connect." },
    { term: "PBX", definition: "Private Branch Exchange" },
    { term: "PC", definition: "Personal Computer" },
    { term: "PCC", definition: "Premises Communication Cable, CSA Cable Designation." },
		{ term: "PHY", definition: "Physical Layer device." },
    { term: "Physical Layer", definition: "Layer one of the seven layer ISO Reference Model for Open Systems Interconnection. The physical layer is responsible for the transmission of signals, such as electrical signals, optical signals, or radio signals, between computing machines." },
    { term: "Picofarad", definition: "One millionth of one millionth of a farad. Abbreviated “pf”." },
    { term: "PIMF", definition: "Pairs in metal foil and early term used for F/FTP and S/FTP cable" },
    { term: "Plastic Fibre", definition: "An optical fibre made of plastic rather than glass." },
    { term: "Plenum", definition: "The air handling space between the walls, under structural floors, and above drop ceilings used to circulate and otherwise handle air in a building. Such spaces are considered plenums only if they are used for air handling. Work spaces are generally not considered plenums." },
    { term: "Plenum Cable", definition: "A cable that is rated as having adequate fire resistance and low smoke producing characteristics for use in air handling spaces (plenum)." },
    { term: "PLC Splitter", definition: "Planar Waveguide Circuit Splitter" },
    { term: "PMD", definition: "Physical Media Dependent or Polarisation Model Dispersion" },
    { term: "4PPoE", definition: "4 Pair Power over Ethernet - see 802.3bt" },
    { term: "PoDL", definition: "Power over Data Line or PoDL (pronounced ‘Poodle’) see 802.3bu" },
    { term: "PoE", definition: "Power over Ethernet, a method of providing low power to end devices over the balanced twisted pair cabling. POE delivers 12.95watts to the end device. POE+ delivers 25.5 watts." },
    { term: "POF", definition: "Plastic Optical Fibre" },
    { term: "POL", definition: "Passive Optical LAN" },
    { term: "PON", definition: "Passive Optical Network" },
    { term: "Polyethylene", definition: "A thermoplastic material having excellent electrical properties." },
    { term: "Polymer", definition: "A substance made of repeating chemical units or molecules. The term is often used in place of plastic, rubber, or elastomer." },
    { term: "Polypropylene", definition: "A thermoplastic material similar to polyethylene but somewhat stiffer and with a higher softening point (temperature)." },
    { term: "Polyurethane", definition: "Broad class of thermoplastic polymers with good abrasion and solvent resistance. Can be solid or cellular (foam)." },
    { term: "Polyvinyl Chloride (PVC)", definition: "A general purpose thermoplastic used for wire and cable insulation and plastics. PVC is know for high flexibility. Often used in nonplenum wire insulation and cable jackets. A modified version of the material may be found in jacketing of some plenum rated cables." },
    { term: "POTS", definition: "Plain Old Telephone System" },
    { term: "Potting", definition: "Sealing by filling with a substance to exclude moisture." },
    { term: "Power Ratio", definition: "The ratio of power appearing at the load to the input power. Expressed in dB." },
    { term: "Premise Cabling", definition: "The entire cabling system on the user’s premises used for transmission of voice, data, video and power." },
    { term: "Pre-wiring", definition: "Wiring installed before walls and ceilings are enclosed." },
    { term: "Propagation Delay", definition: "Time required for a signal to pass from the input to the output of a device." },
    { term: "Protocol", definition: "A set of agreed upon rules and message formats for exchanging information among devices on a network." },
    { term: "PSELFEXT", definition: "Power Sum Equal Level Far End Crosstalk" },
    { term: "PSNEXT", definition: "Power Sum Near End Crosstalk" },
    { term: "Public Switched Network", definition: "Any common carrier network that provides circuit switching between public users, such as the public telephone network, telex or MCI’s Execunet." },
    { term: "PUE", definition: "Power Usage Effectiveness" },
    { term: "Pull Strength, Pull Tension", definition: "The pulling force that can be applied to a cable without affecting the specified characteristics of the cable." },
    { term: "R", definition: "Symbol for Resistance" },
    { term: "RAS", definition: "Remote Access Server. A device which enables external devices to access network facilities. The RAS will generally be equipped with analogue modems and/or ISDN terminal adapters to enable remote users to “dial-in”. The RAS will incorporate security features including password control, dial back, CLI recognition and hardware handshaking." },
    { term: "RCDD", definition: "Registered Communication Distribution Designer. A certification of BICSI, an industry organisation, for individuals qualified to consult and design telecommunications distribution systems." },
    { term: "Reflection", definition: "A return of electromagnetic energy that occurs at an impedance mismatch in a transmission line, such as a LAN cable. Reflection causes signal loss, increased noise, and cancellation of the signal." },
    { term: "Refractive Index", definition: "The ratio of the speed of light in a vacuum to its velocity in a transmitting medium, such as an optical fibre core." },
    { term: "Repeater", definition: "A device that receives, amplifies (and sometimes reshapes), and retransmits a signal. It is used to boost signal levels and extend the distance a signal can be transmitted. It can physically extend the distance of a LAN or connect two LAN segments." },
    { term: "Resistance", definition: "In dc circuits, the opposition a material offers to current flow, measured in ohms. In ac circuits, resistance is the real component of impedance and may be higher than the value measured at dc." },
    { term: "Reversed Pair", definition: "A wiring error in twisted pair cabling where the conductors of a pair are reversed between connector pins at each end of a cable." },
    { term: "RFI", definition: "Radio Frequency Interference. Electromagnetic interference at radio frequencies." },
    { term: "RFP", definition: "Request for Proposal" },
    { term: "RFQ", definition: "Request for Quote (or Quotation)" },
    { term: "Ripcord", definition: "A cord placed directly under the jacket of a cable in order to facilitate stripping (removal) of the jacket." },
    { term: "Riser", definition: "The conduit or path between floors of a building into which telephone, networking, and other utility cables are placed to bring service from one floor to another." },
    { term: "Riser Cable", definition: "A type of cable used in vertical building shafts, such as telecommunications and utility shafts. Riser cable typically has more mechanical strength than general use cable and has an intermediate fire protection rating." },
    { term: "RJ", definition: "A term from the telephone industry, used for jacks (connectors) that were registered for use with particular types of telephone services." },
    { term: "RJ45", definition: "A USOC code identifying an 8 pin modular plug or jack used with unshielded twisted pair cable. Officially, an RJ45 connector is a telephone connector designed for voice grade circuits only. RJ45 type connectors with better signal handling characteristics are called 8 pin connectors in most standards documents, though most people continue to use the RJ45 name for all 8 pin connectors." },
    { term: "Router", definition: "A device which controls the routing of information on a network. The term strictly refers to a layer 3 (OSI model) device which can interpret network addressing information and route data packets accordingly. Routers undertake broadly the same function as bridges but can dynamically manage bandwidth more effectively and can provide enhanced levels of security." },
    { term: "Rx", definition: "Receive" },
    { term: "SAN", definition: "Storage Area Network" },
    { term: "SC Connector", definition: "A fibre optic connector having a 2.5mm ferrule, push pull latching mechanism, and the ability to be snapped together to form duplex and multifibre connectors." },
    { term: "Screened Twisted Pair, (STP)", definition: "Generic term for screened cables irrespective of Category or construction of the screen and covers from an F/UTP Cable, through to S/FTP variants." },
    { term: "SCP", definition: "Service Concentration Point- as defined in BS EN 50173-6 - Distributed Building Services" },
    { term: "SCS", definition: "Structured Cabling System" },
    { term: "Secondary Equipment Room (SER)", definition: "Secondary room typically situated on a Floor or Area of the building and services the Outlets in that area." },
    { term: "Separator", definition: "Pertaining to wire and cable, a layer of insulating material such as textile, paper, Mylar, etc. which is placed between a conductor and its dielectric, between a cable jacket and the components it covers, or between various components of a multiple conductor cable. It can be utilised to improve stripping qualities, flexibility, or can offer additional mechanical or electrical protection to the components it separates." },
    { term: "S/FTP", definition: "Screened Braid outer with individual foil screened twisted pairs" },
    { term: "Sheath", definition: "see Jacket" },
    { term: "Shield", definition: "A metallic foil or multiwire screen mesh that is used to prevent electromagnetic fields from penetrating or exiting a transmission cable. Also referred to as a “screen”." },
    { term: "SI Unit", definition: "International System of Units - there are 7 base units of measure from which all other units of measure are derived (see SI Base Units table)" },
    { term: "Signal to noise ratio (SNR)", definition: "The ratio of received signal level to received noise level, expressed in dB. Abbreviated S/N. A higher S/N ratio indicates better channel performance." },
    { term: "Simplex Transmission", definition: "Data transmission over a circuit capable of transmitting in one preassigned direction only." },
    { term: "Single Mode Fibre", definition: "An optical fibre that will allow only one mode to propagate. The fibre has a very small core diameter of approximately 9 µm. It permits signal transmission at extremely high bandwidth and allows very long transmission distances." },
    { term: "Skew Rays", definition: "A ray that does not intersect the fibre axis. Generally, a light ray that enters the fibre at a very high angle." },
    { term: "SLA", definition: "Service Level Agreement. A term commonly used within the IT industry to refer to the service standards which a service provider agrees to deliver to a user. Initially used in contractual arrangements with third parties but now commonly used as an internal agreement within organisations." },
    { term: "SMA Connector", definition: "A threaded type fibre optic connector. The 905 version is a straight ferrule design, whereas the 906 is a stepped ferrule design." },
    { term: "SMTP", definition: "Simple Mail Transfer Protocol. The protocol used by devices to communicate with a network management system." },
    { term: "SNMP", definition: "Simple Network Management Protocol. The protocol used by devices to communicate with a network management system." },
    { term: "SO", definition: "Service Outlet -as defined in BS EN 50173-6 - Distributed Building Services" },
    { term: "SONET", definition: "see Synchronous Optical Network." },
    { term: "Speed of Light", definition: "In a vacuum, 299,800,000 meters per second." },
    { term: "Splice", definition: "A joining of conductors generally from separate sheaths." },
    { term: "Splice Closure", definition: "A device used to protect a cable or wire splice." },
    { term: "Split Pair", definition: "A wiring error in twisted pair cabling where one of a pair’s wires is interchanged with one of another pair’s wires." },
    { term: "Split pair conditions", definition: "may be determined with a transmission test. Simple DC continuity testing will not reveal the error, because the correct pin to pin continuity exists between ends. However, the error may result in impedance mismatch, excessive crosstalk, susceptibility to interference, and signal radiation." },
    { term: "SRL", definition: "see Structural Return Loss" },
    { term: "ST Connector", definition: "Designation for the “straight tip” connector developed by AT&T. This fibre optic connector features a physically contacting non rotating 2.5mm ferrule design and bayonet connector to adapter mating. Used with Ethernet 10Base FL and FIORL links." },
    { term: "Standing Wave", definition: "The stationary pattern of waves produced by two waves of the same frequency travelling in opposite directions on the same transmission line. The existence of voltage and current maxima and minima along a transmission line is a result of reflected energy from an impedance mismatch." },
    { term: "Standing Wave Ratio (swr)", definition: "A ratio of the maximum amplitude to the minimum amplitude of a standing wave stated in current or voltage amplitudes." },
    { term: "Star Topology", definition: "A topology in which each outlet/connector is wired directly to the distribution device." },
    { term: "STP", definition: "see Screened Twisted Pair" },
    { term: "Strength Member", definition: "That part of a fibre optic cable that increases the cable’s tensile strength and serves as a load bearing component. Usually made of Kevlar aramid yarn, fibreglass filaments, or steel strands." },
    { term: "Structural Return Loss (SRL)", definition: "A measure of the impedance uniformity of a cable. It measures energy reflected due to structural variations in the cable. A higher SRL number indicates better performance (more uniformity and lower reflections)." },
    { term: "Structured Wiring", definition: "Telecommunications cabling that is organised into a hierarchy of wiring termination and interconnection structures. The concept of structured wiring is used in the common standards from the TIA and EIA." },
    { term: "Surge Suppression", definition: "The process by which transient voltage surges are prevented from reaching sensitive electronic equipment." },
    { term: "Switch", definition: "Generic term for a PABX. Also a device employed in LANs to partition networks. A LAN switch (Ethernet or token ring) is strictly a matrix of bridges that isolates Ethernet collision domains." },
    { term: "SWDM", definition: "Shortwave, Wavelength Division Mulitplexing" },
    { term: "Synchronous", definition: "Transmission in which the data character and bits are transmitted at a fixed rate with the transmitter and receiver being synchronised." },
    { term: "Synchronous Digital Hierarchy (SDH)", definition: "International standard for optical digital transmission at hierarchical rates from 155 Mbps to 2.5 Gbps and beyond." },
    { term: "Synchronous Optical Network (SONET)", definition: "A USA standard for optical digital transmission at hierarchical rates from 155 Mbps to 2.5 Gbps and beyond." },
    { term: "T1", definition: "T1 is a 1.544 Mbps multichannel digital transmission system for voice or data provided by long distance carriers. Also referred to as DS1 (Data Services)." },
    { term: "T3", definition: "T3 is a 44.736 Mbps multichannel digital transmission system for voice or data provided by long distance carriers. Also referred to as DS3 (Data Services)." },
    { term: "TC", definition: "Telecommunications Cross Connect." },
    { term: "TCP", definition: "Transmission Control Protocol. Often used as a suite with IP as TCP/IP with jointly forms the protocols used on the Internet." },
    { term: "TDR", definition: "See Time Domain Reflectometry" },
    { term: "Telecommunications Closet", definition: "Cupboard or Closet containing equipment and structured cabling infrastructure to support a small area of the Floor within a Building." },
    { term: "Telecommunications Equipment Room", definition: "see Equipment Room" },
    { term: "Telecommunications Outlet (TO)", definition: "Provides the means for the user to connect end equipment to the Structured Cabling System (SCS) by way of an equipment/patch cord" },
    { term: "Thicknet", definition: "Ethernet 10Base5 coaxial cable" },
    { term: "Thinnet", definition: "Ethernet 10Base2 coaxial cable. Also called “cheapernet”." },
    { term: "TIA", definition: "Telecommunications Industry Association. Body which authored the TIA/EIA 568 A “Commercial Building Telecommunications Wiring Standard” in conjunction with EIA." },
    { term: "Time Domain Reflectometry", definition: "A technique for measuring cable lengths by timing the period between a test pulse and the reflection of the pulse from an impedance discontinuity on the cable. The returned waveform reveals many undesired cable conditions, including shorts, opens, and transmission anomalies due to excessive bends or crushing. The length to any anomaly, including the unterminated cable end, may be computed from the relative time of the wave return and nominal velocity of propagation of the pulse through the cable. See also Optical Time Domain Reflectometry." },
    { term: "Token Ring", definition: "A local area network (LAN) protocol defined in the IEEE 802.5 standard in which computers access the network through a token passing scheme. Uses a star wired ring topology." },
    { term: "Topology", definition: "The physical or logical interconnection pattern of a network." },
    { term: "Transceiver", definition: "A combination of the words TRANSmitter and reCEIVER. A transceiver is the set of electronics that send and receive signals on the Ethernet media system. Transceivers may be small outboard devices, or may be built into an Ethernet port. Also called Media Attachment Unit, or MAU." },
    { term: "Transition Point", definition: "A location in the horizontal cabling where flat undercarpet cable connects to round cable." },
    { term: "Transmission Media", definition: "Anything such as wire, coaxial cable, fibre optics, air or vacuum, that is used to carry a signal." },
    { term: "Transmitter", definition: "A device that converts electrical signals for transmission to a distant point. In fibre optic systems, the electronic component that converts electrical energy to light energy." },
    { term: "TSB", definition: "Telecommunications Systems Bulletin" },
    { term: "Turn-key", definition: "A contractual arrangement in which one party designs and installs a system and “turns over the keys” to another party who will operate the system." },
    { term: "Twinaxial Cable, Twinax", definition: "A type of communication transmission cable consisting of two center conductors surrounded by an insulating spacer which in turn is surrounded by a tubular outer conductor (usually a braid, foil or both). The entire assembly is then covered with an insulating and protective outer layer. It is similar to coaxial cable except that there are two conductors at the center." },
    { term: "Twisted Pair", definition: "A multiple conductor cable whose component wires are paired together, twisted, and enclosed in a single jacket. Each pair consists of two insulated copper wires twisted together. When driven as a balanced line, the twisting reduces the susceptibility to external interference and the radiation of signal energy. Most twisted pair cabling contains either 2, 4, or 25 pairs of wires." },
    { term: "Type 1", definition: "150 ohm shielded twisted pair (STP) cabling conforming to the IBM Cabling System Specifications. Two twisted pairs of 22 AWG solid conductors for data communications are enclosed in a braided shield covered with a sheath. Tested for operation up to 16 MHz." },
    { term: "Type 1A", definition: "Enhanced version of IBM Type 1 cable rated for operation up to 300 Mhz. Meets electrical specifications for 150 ohm STP - A Cable as documented in the TIA/EIA 568 - A standard." },
    { term: "U Height", definition: "Equates to 1.75 inches (44.45 mm) and is used to measure vertical Usable space in IT equipment cabinets. Most IT equipment is sized in U’s." },
    { term: "U/FTP", definition: "Unscreened outer with individual foil screened twisted pairs." },
    { term: "UKCA", definition: "UK Conformity Assessed" },
    { term: "UL", definition: "Underwriters Laboratories, Inc." },
    { term: "Unscreened Twisted Pair (UTP)", definition: "Generic Term for all Unscreened cable constructions" },
    { term: "UPoE", definition: "Universal Power over Ethernet, Cisco’s proprietary 4 pair powering form of POE delivering 51watts powered" },
    { term: "VA", definition: "Volt-ampere. A designation of power in terms of voltage and current." },
    { term: "Vampire Tap", definition: "see Tap" },
    { term: "VFL", definition: "Visual Fault Locator - used in optical fibre fault diagnostics" },
    { term: "Voice Grade", definition: "A term used for twisted pair cable used in telephone systems to carry voice signals." },
    { term: "Volt", definition: "The unit of electrical potential. One volt is the electrical potential that will cause one ampere of current to flow through one ohm of resistance." },
    { term: "WAN", definition: "Wide Area Network. The term used to describe any network which is not restricted to a limited geographical area." },
    { term: "Watt", definition: "A unit of electrical power. One watt is equivalent to the power represented by one ampere of current flowing through a load with a voltage drop of one volt in a dc circuit." },
    { term: "Wavelength", definition: "The distance between successive peaks or nodes of a wave." },
    { term: "Wavelength Division Multiplexing (WDM)", definition: "The process of combining many signals on the basis of difference in their wavelengths." },
    { term: "Wiring Closet", definition: "See Telecommunications Closets" },
    { term: "WireMap", definition: "The first test carried out on a copper network for continuity and that each conductor of a four-pair cable is connected correctly." },
    { term: "λ", definition: "wavelength, measured in nm (nano-metres) for optical fibre" },
    { term: "µm", definition: "Micron" },
    { term: "Glossary details compiled with assistance from Fluke Networks." }
  ];

  return (
    <div>
      <MainMenu />
      <h1>Glossary of Terms</h1>
      <ul>
        {terms.map((term, index) => (
          <li key={index}>
            <strong>{term.term}:</strong> {term.definition}
          </li>
        ))}
      </ul>
    </div>
  );
};

export default Glossary;	
				