
    import React from 'react';
    import MainMenu from '../components/MainMenu';

    const Glossary = () => {
      const terms = [
        { term: "10GBase-SR", definition: "IEEE 802.3an Standard for 'Short Reach' using 850nm lasers can transmit up to 300 metres using 50 micron OM3 multimode fibre." },
        { term: "10GBase-LR", definition: "IEEE 802.3an Standard for 'Long Reach' using 1310nm lasers can transmit up to 10km using OS1 Single mode fibre." },
        { term: "10GBase-T", definition: "IEEE 802.3an Standard released in 2006, to provide 10Gbit/s Ethernet connections over unshielded or shielded twisted pair cables, over distances up to 100 metres." },
        { term: "1000Base-LX", definition: "IEEE 802.3 shorthand term for 1000 Mbps Gigabit Ethernet based on 8B/10B signaling using long wavelength laser transmitters over fibre optic cable." },
        { term: "1000Base-SX", definition: "IEEE 802.3 shorthand term for 1000 Mbps Gigabit Ethernet based on 8B/10B signaling using short wavelength laser transmitters over fibre optic cable." },
        { term: "1000Base-T", definition: "IEEE 802.3 shorthand term for 1000 Mbps Gigabit Ethernet over twisted pair cable." },
        { term: "1000Base-X", definition: "IEEE 802.3 shorthand term for any 1000 Mbps Gigabit Ethernet based on 8B/10B signaling. Includes 1000Base-CX, 1000Base-LX and 1000Base-SX." },
        { term: "100Base-FX", definition: "IEEE 802.3 shorthand term for 100 Mbps Fast Ethernet based on 4B/5B signal encoding over fibre optic cable." },
        { term: "100Base-T", definition: "IEEE 802.3 shorthand term for entire 100 Mbps Fast Ethernet system." },
        { term: "100Base-TX", definition: "IEEE 802.3 shorthand term for 100 Mbps Fast Ethernet based on 4B/5B signal encoding and using two pairs of category 5 twisted pair cable." },
        { term: "100Base-X", definition: "IEEE 802.3 shorthand term for any 100 Mbps Fast Ethernet system based on 4B/5B signal encoding. Includes 100Base-TX and 100Base-FX." },
        { term: "10Base2", definition: "IEEE 802.3 shorthand term for 10 Mbps Ethernet based on Manchester signal encoding over thin coaxial cable. Also called 'Thinnet' or 'Cheapernet'." },
        { term: "10Base5", definition: "IEEE 802.3 shorthand term for 10 Mbps Ethernet based on Manchester signal encoding over thick coaxial cable. Also called 'Thicknet'." },
        { term: "10Base-T", definition: "IEEE 802.3 shorthand term for 10 Mbps Ethernet based on Manchester signal encoding over category 3 or better twisted pair cable." },
        { term: "10Base-T1S", definition: "IEEE 802.3 shorthand term for 10 Mbps Ethernet over Single Pair, Short Reach." },
        { term: "10Base-T1L", definition: "IEEE 802.3 shorthand term for 10 Mbps Ethernet over Single Pair, Long Reach up to 1Km." },
        { term: "100Base-T1S", definition: "IEEE 802.3 shorthand term for 100Mbps Ethernet over Single Pair, Short Reach." },
        { term: "ACP", definition: "Area Connection Point." },
        { term: "ANSI", definition: "American National Standards Institute." },
        { term: "Asynchronous", definition: "Transmission where sending and receiving devices are not synchronized. Data must carry signals to indicate data division." },
        { term: "ATM", definition: "Asynchronous Transfer Mode. A networking protocol which can support multimedia (i.e. Voice, data, video, text etc.) communications." },
        { term: "Attenuation", definition: "The decrease in magnitude of a signal as it travels through any transmission medium such as a cable or optical fibre. Measured in dB per unit of length." },
        { term: "ACR (Attenuation Crosstalk Ratio)", definition: "The difference between attenuation and crosstalk, measured in dB, at a given frequency. A quality factor for cabling to assure that signal sent down a twisted pair is stronger at the receiving end of the cable than any interference imposed on the same pair by crosstalk from other pairs." },
        { term: "ACR-F", definition: "Attenuation Crosstalk Ratio Far End." },
        { term: "AWG", definition: "American Wire Gage - A wire diameter specification. The smaller the AWG number, the larger the wire diameter." },
        { term: "Back reflection", definition: "The light reflected back towards the source from the fibre optic ends and deformations." },
        { term: "Backscatter", definition: "Another term for Back Reflection, reflection of signal back to the direction from which they came." },
        { term: "Backbone", definition: "Term used to refer to the common central elements of any communications network. The backbone is the part of the network which connects all the individual network components." },
        { term: "Bandwidth", definition: "The range of frequencies required for proper transmission of a signal. Expressed in Hertz (cycles per second). The higher the bandwidth, the more information that can be carried." },
        { term: "Baud", definition: "The number of changes in signal per second. A given baud rate does not necessarily transmit an equal number of bits/sec." },
        { term: "BD", definition: "Building Distributor - main comms room for distribution of services throughout the building." },
        { term: "BEF", definition: "Building Entrance Facility - used by service providers such as BT, Virgin Media etc." },
        { term: "Bend Loss", definition: "A form of increased attenuation in an optical fibre caused by an excessively small bend radius. The attenuation may be permanent if micro fractures caused by the bend continue to affect transmission of the light signal." },
        { term: "Bend Radius", definition: "Radius of curvature that a fibre optic or metallic cable can bend before the risk of breakage or increased attenuation occurs." },
        { term: "BICSI", definition: "Building Industry Consulting Service International." },
        { term: "Bit", definition: "One binary digit." },
        { term: "BER (Bit Error Rate)", definition: "A measure of data integrity, expressed as the ratio of received bits that are in error, relative to the amount of bits received. Often expressed as a negative power of ten." },
        { term: "Bit Stream", definition: "A continuous transfer of bits over some medium." },
        { term: "BMS", definition: "Building Management System." },
        { term: "BNC", definition: "A coaxial connector that uses a 'bayonet' style turn and lock mating method. Used with RG58 or smaller coaxial cable. Used with 10Base2 Ethernet thin coaxial cable. BNC is an acronym for Bayonet Neill Concelman." },
        { term: "BO", definition: "Broadcast Outlet (TV Outlet)." },
        { term: "BOYD", definition: "Bring your own device'." },
        { term: "BPS", definition: "Bits per second." },
        { term: "Braid", definition: "Fine wires interwoven to form a tubular flexible structure that may be applied over one or more wires for the purpose of shielding." },
        { term: "BRI", definition: "ISDN Basic Rate Interface." },
        { term: "Broadband", definition: "A transmission facility having a bandwidth sufficient to carry multiple voice, video or data channels simultaneously." },
        { term: "Broadcast", definition: "Sending data to more than one receiving device at a time." },
        { term: "Buffer", definition: "A protective coating over a strand of optical fibre." },
        { term: "Bus Topology", definition: "In general, a physical layout of network devices in which all devices must share a common medium to transfer data, and no two devices may transmit simultaneously." },
        { term: "Byte", definition: "A group of 8 bits." },
        { term: "Campus", definition: "The buildings and grounds of a complex, such as a university, college, industrial park or military establishment." },
        { term: "Carrier", definition: "An electrical signal of a set frequency that can be modulated in order to carry data." },
        { term: "Category 3, Cat 3", definition: "Balanced twisted-pair copper cable and component specifications characterised in a frequency range up to 16 MHz. with a characteristic Impedance of 100Ohm." },
        { term: "Category 5e, Cat 5e", definition: "Balanced twisted-pair copper cable and component specifications characterised in a frequency range up to 100 MHz. with a characteristic Impedance of 100Ohm." },
        { term: "Category 6, Cat 6", definition: "Balanced twisted-pair copper cable and component specifications characterised in a frequency range up to 250 MHz. with a characteristic impedance of 100Ohm." },
        { term: "Category 6A, Cat 6A", definition: "Balanced twisted-pair copper cable and component specifications characterised in a frequency range up to 500 MHz. with a Characteristic impedance of 100Ohm." },
        { term: "Category 7, Cat 7", definition: "Balanced twisted-pair copper cable and component specifications characterised in a frequency range up to 600 MHz. with a characteristic impedance of 100Ohm." },
        { term: "Category 7A, Cat 7A", definition: "Balanced twisted-pair copper cable and component specifications characterised in a frequency range up to 1000 MHz.(1Ghz) with a characteristic Impedance of 100Ohm." },
        { term: "Category 8, Cat 8", definition: "Whilst not yet ratified this is intended to support short 40Gb links within the Data Centre environment. It will be a balanced twisted-pair copper cable and component specifications characterised in a frequency range of up to 2GHz with a characteristic Impedance of 100Ohm." },
        { term: "CATV", definition: "Community Antenna Television." },
        { term: "CCTV", definition: "Closed Circuit TV." },
        { term: "CD", definition: "Campus Distributor - Main campus communication room or facility." },
        { term: "CDDI", definition: "Copper Distributed Data Interface. A version of FDDI that uses copper wire media instead of fibre optic cable." },
        { term: "CENELEC", definition: "European Committee for Electrotechnical Standardization." },
        { term: "Channel", definition: "The end to end transmission path between two points at which application specific equipment is connected." },
        { term: "Channel Insertion Loss", definition: "For fibre optic links, the static loss of a link between a transmitter and receiver. It includes the loss of the fibre, connectors, and splices." },
        { term: "Characteristic Impedance", definition: "The impedance that an infinitely long transmission line would have at its input terminal. If a transmission line is terminated in its characteristic impedance, it will appear (electrically) to be infinitely long, thus minimizing signal reflections from the end of the line." },
        { term: "Chromatic Dispersion", definition: "Synonym for 'material dispersion'. Characteristic of long fibre runs." },
        { term: "CIBSE", definition: "Chartered Institution of Building Service Engineers." },
        { term: "Class C", definition: "ISO/IEC 11801 designation for twisted pair cabling rated to 16 MHz. Corresponds to the TIA/EIA Category 3 cabling standard." },
        { term: "Class D", definition: "ISO/IEC 11801 designation for twisted pair cabling rated to 100 MHz. Using Category 5e components it corresponds to the TIA/EIA Category 5e cabling standard." },
        { term: "Class E", definition: "ISO/IEC 11801 designation for twisted pair cabling rated to 250 MHz. Using Category 6 components it corresponds to the TIA/EIA Category 6 cabling standard." },
        { term: "Class EA", definition: "ISO/IEC 11801 designation for twisted pair cabling rated to 500 MHz. Using Category 6A components it corresponds to the TIA/EIA Category 6A cabling standard." },
        { term: "Class F", definition: "ISO/IEC 11801 designation for twisted pair cabling rated to 600 MHz, TIA/EIA does not recognise Category 7." },
        { term: "Class FA", definition: "ISO/IEC 11801 designation for twisted pair cabling rated to 1000 MHz. (1Ghz) TIA/EIA does not recognise Category 7A." },
        { term: "Class I", definition: "ISO/IEC 11801 designation for twisted pair cabling rated to 1600 MHz. (1.6Ghz) this does not correspond to TIA/EIA Category 8 cabling standard." },
        { term: "Class II", definition: "ISO/IEC 11801 designation for twisted pair cabling rated to 2000 MHz. (2Ghz) this does correspond to the TIA/EIA Category 8 cabling standard." },
        { term: "CLI", definition: "Calling Line Identity. The term used to describe the feature whereby the telephone number of a calling party is presented to the equipment of the called party." },
        { term: "CDCDP", definition: "Certified Data Centre Design Professional." },
        { term: "CDCTP", definition: "Certified Data Centre Technical Professional." },
        { term: "CNCI", definition: "Certified Network Cable Installer." },
        { term: "CNIT", definition: "Certified Network Infrastructure Technician." },
        { term: "CNID", definition: "Certified Network Infrastructure Designer." },
        { term: "CNIDP", definition: "Certified Network Infrastructure Design Professional." },
        { term: "CO", definition: "Control Outlet - outlet used by the Building Control System such as BMS." },
        { term: "Coax, Coaxial Cable", definition: "A type of communication transmission cable in which a solid center conductor is surrounded by an insulating spacer which in turn is surrounded by a tubular outer conductor (usually a braid, foil or both). The entire assembly is then covered with an insulating and protective outer layer." },
        { term: "Collision", definition: "When electrical signals from two or more devices sharing a common data transfer medium crash into one another. This commonly happens on Ethernet type systems." },
        { term: "Conductor", definition: "A material that offers low resistance to the flow of electrical current." },
        { term: "Conduit", definition: "A rigid or flexible metallic or nonmetallic raceway of circular cross section in which cables are housed for protection and to prevent burning cable from spreading flames or smoke in the event of a fire." },
        { term: "Consolidation Point (CP)", definition: "A CP is a location for interconnection between the permanently installed horizontal cables the TR and the horizontal cables extending to the telecommunications outlet (TO)." },
        { term: "Continuity", definition: "An uninterrupted pathway for electrical signals." },
        { term: "Core", definition: "The central region of an optical fibre through which light is transmitted." },
        { term: "CPD", definition: "Continuing Professional Development." },
        { term: "CPR", definition: "Construction Products Regulation." },
        { term: "CPR", definition: "Coupled Power Ratio which is used when testing optical fibre cables." },
        { term: "Cross Connect", definition: "A facility enabling the termination of cable elements and their interconnection, and/or cross connection, primarily by means of a patch cord or jumper." },
        { term: "Cross Connection", definition: "A connection scheme between cabling runs, subsystems, and equipment using patch cords or jumpers that attach to connecting hardware at each end." },
        { term: "Crossover Cable", definition: "A twisted pair patch cable wired in such a way as to route the transmit signals from one piece of equipment to the receive signals of another piece of equipment, and vice versa." },
        { term: "Crosstalk", definition: "The coupling of unwanted signals from one pair within a cable to another pair. Crosstalk can be measured at the same (near) end or far end with respect to the signal source." },
        { term: "CSMA/CD", definition: "Carrier Sense Multiple Access with Collision Detect." },
        { term: "CTI", definition: "Computer Telephony Integration. The integration of computer and telephone systems to support intelligent applications." },
        { term: "Customer Premises", definition: "Buildings, offices, and other structures under the control of a telecommunications customer." },
        { term: "CWDM", definition: "Course Wavelength Disiion Multiplexing." },
        { term: "CW1128", definition: "External grade multipair voice cable that meets the (BT) British Telecom specification." },
        { term: "CW1308", definition: "Internal grade multipair voice cable that meets the (BT) British Telecom specification." },
        { term: "CW1308B", definition: "Internal/External, with earth grade multipair voice cable that meets the (BT) British Telecom specification." },
        { term: "Data Connector", definition: "A four position connector for 150 - ohm STP used primarily with Token Ring networks." },
        { term: "dB", definition: "Decibel. A unit for measuring the relative strength of a signal. Usually expressed as the logarithmic ratio of the strength of a transmitted signal to the strength of the original signal. A decibel is one tenth of a 'bel'." },
        { term: "DC Loop Resistance", definition: "The total DC resistance of a cable. For twisted pair cable, it includes the round trip resistance, down one wire of the pair and back up the other wire." },
        { term: "DCE", definition: "Data Communications Equipment. Any equipment that connects to Data Terminal Equipment (DTE) to allow transmission between DTEs." },
        { term: "DCIE", definition: "Data Centre Infrastructure Efficiency." },
        { term: "DDI", definition: "Direct Dialing Inward. This facility enables external callers to dial directly to PABX extensions (without going via the switchboard) by inserting a prefix in front of the extension number." },
        { term: "Demarcation Point", definition: "A point where the operational control or ownership changes, such as the point of interconnection between telephone company facilities and a user's building or residence." },
        { term: "Dielectric", definition: "An insulating (non conducting) material." },
        { term: "Direct Current (DC)", definition: "An electric current that flows in one direction and does not reverse direction as with 'alternating current'." },
        { term: "Dispersion", definition: "The phenomenon in an optical fibre whereby light photons arrive at a distant point in a different phase than they entered the fibre. Dispersion causes receive signal distortion that ultimately limits the bandwidth and usable length of the fibre cable." },
        { term: "Distribution Frame", definition: "A structure with terminations for connecting the permanent cabling of a facility in a manner that interconnections or cross connects may be readily made." },
        { term: "Drain Wire", definition: "An uninsulated wire in contact with a shield throughout its length. Used to terminate the shield." },
        { term: "DTE", definition: "Data Terminal Equipment. Any piece of equipment at which a communications path begins or ends." },
        { term: "Duct", definition: "A single enclosed raceway for wires or cable or an enclosure in which air is moved." },
        { term: "Duplex", definition: "A circuit used to transmit signals simultaneously in both directions or two receptacles or jacks in a common housing which accept two plugs." },
        { term: "DWDM", definition: "Dense Wavelength Division Multiplexing." },
        { term: "E1/E3", definition: "The